### ISSUE TITLE
Can't do nested class assignment and assign instance variable at the same time

### ISSUE THREAD

**Issue by bouk** [juliankrispel/decaf#53]
When trying to compile (on master, so it includes your nested class assignment fix)

```
class A.B
  c: (@d) ->
```

I get

```
TypeError: Cannot read property 'constructor' of null
  at mapExpression (/Users/bouke/repos/decaf/dist/index.js:969:18)
  at mapClassExpression (/Users/bouke/repos/decaf/dist/index.js:350:45)
  at mapExpression (/Users/bouke/repos/decaf/dist/index.js:1000:12)
  at /Users/bouke/repos/decaf/dist/index.js:227:12
  at Array.map (native)
  at mapArguments (/Users/bouke/repos/decaf/dist/index.js:216:15)
  at mapCall (/Users/bouke/repos/decaf/dist/index.js:247:50)
  at mapExpression (/Users/bouke/repos/decaf/dist/index.js:1019:12)
  at mapStatement (/Users/bouke/repos/decaf/dist/index.js:492:49)
  at /Users/bouke/repos/decaf/dist/index.js:497:12
  at Array.map (native)
  at mapBlockStatements (/Users/bouke/repos/decaf/dist/index.js:496:27)
  at mapBlockStatement (/Users/bouke/repos/decaf/dist/index.js:504:23)
  at transpile (/Users/bouke/repos/decaf/dist/index.js:1118:17)
  at /Users/bouke/repos/decaf/node_modules/lodash/internal/createFlow.js:67:31
  at Object.compile (/Users/bouke/repos/decaf/dist/index.js:1134:10)
  at runByFile (/Users/bouke/repos/decaf/bin/decaf:52:20)
  at /Users/bouke/repos/decaf/bin/decaf:44:7
  at Array.forEach (native)
  at run (/Users/bouke/repos/decaf/bin/decaf:28:9)
  at Object.<anonymous> (/Users/bouke/repos/decaf/bin/decaf:25:1)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Function.Module.runMain (module.js:447:10)
  at startup (node.js:139:18)
  at node.js:999:3
```

This doesn't happen if I don't do `@d` or if I don't do `A.B`

**Comment by juliankrispel** [comment]
fixed in #56
