### ISSUE TITLE
Calling method on result of comprehension

### ISSUE THREAD

**Issue by bouk** [juliankrispel/decaf#86]
Input:

```
(a for a of b).sort()
```

Error:

```
TypeError: Cannot read property 'constructor' of undefined
  at mapExpression (/Users/bouke/repos/decaf/dist/index.js:1034:18)
  at mapForExpression (/Users/bouke/repos/decaf/dist/index.js:945:173)
  at mapExpression (/Users/bouke/repos/decaf/dist/index.js:1069:12)
  at mapExpression (/Users/bouke/repos/decaf/dist/index.js:1043:55)
  at mapMemberProperties (/Users/bouke/repos/decaf/dist/index.js:103:12)
  at mapMemberExpression (/Users/bouke/repos/decaf/dist/index.js:115:10)
  at mapExpression (/Users/bouke/repos/decaf/dist/index.js:1037:12)
  at mapCall (/Users/bouke/repos/decaf/dist/index.js:244:12)
  at mapExpression (/Users/bouke/repos/decaf/dist/index.js:1092:12)
  at mapStatement (/Users/bouke/repos/decaf/dist/index.js:521:49)
  at /Users/bouke/repos/decaf/dist/index.js:526:12
  at Array.map (native)
  at mapBlockStatements (/Users/bouke/repos/decaf/dist/index.js:525:27)
  at mapBlockStatement (/Users/bouke/repos/decaf/dist/index.js:533:23)
  at transpile (/Users/bouke/repos/decaf/dist/index.js:1197:17)
  at /Users/bouke/repos/decaf/dist/index.js:1214:12
  at /Users/bouke/repos/decaf/node_modules/lodash/internal/createFlow.js:67:31
  at Object.compile (/Users/bouke/repos/decaf/dist/index.js:1217:10)
  at runByFile (/Users/bouke/repos/decaf/bin/decaf:52:20)
  at /Users/bouke/repos/decaf/bin/decaf:44:7
  at Array.forEach (native)
  at run (/Users/bouke/repos/decaf/bin/decaf:28:9)
  at Object.<anonymous> (/Users/bouke/repos/decaf/bin/decaf:25:1)
  at Module._compile (module.js:413:34)
  at Object.Module._extensions..js (module.js:422:10)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Function.Module.runMain (module.js:447:10)
  at startup (node.js:139:18)
  at node.js:999:3
```

**Comment by juliankrispel** [comment]
@bouk really appreciate all the work you put into testing this on an actual codebase. I'll do my best to fix these issues in a timely manner.

How's it going in general btw? Are you actually attempting to transform all cs files in the shopify codebase?

**Comment by bouk** [comment]
I'm testing how feasible it is to do automatic translation.
